spring:
  datasource:
    url: jdbc:h2:file:./data/mydb;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false

  liquibase:
    enabled: true