--liquibase formatted sql

--changeset razvi:01-create-identity-cards-table
CREATE TABLE identity_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_model VARCHAR(5) NOT NULL,
    cnp VARCHAR(13) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    series VARCHAR(5),
    number VARCHAR(9) NOT NULL,
    address VARCHAR(150),
    sex VARCHAR(1) NOT NULL,
    citizenship VARCHAR(25) NOT NULL,
    birthplace VARCHAR(50),
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    issued_by VARCHAR(25) NOT NULL,
    date_of_birth DATE,
    mrz_line_1 VARCHAR(45) NOT NULL,
    mrz_line_2 VARCHAR(45) NOT NULL,
    mrz_line_3 VARCHAR(45) NULL
);